# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rack-codehighlighter}
  s.version = "0.4.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wlodek Bzyl"]
  s.date = %q{2011-07-24}
  s.description = %q{Rack Middleware for Code Highlighting.}
  s.email = %q{matwb@univ.gda.pl}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown",
    "TODO"
  ]
  s.files = [
    "LICENSE",
    "Rakefile",
    "TODO",
    "VERSION.yml",
    "examples/app.rb",
    "examples/check.rb",
    "examples/coderay.ru",
    "examples/config.ru",
    "examples/public/javascripts/lang-css.js",
    "examples/public/javascripts/lang-hs.js",
    "examples/public/javascripts/lang-lisp.js",
    "examples/public/javascripts/lang-lua.js",
    "examples/public/javascripts/lang-ml.js",
    "examples/public/javascripts/lang-proto.js",
    "examples/public/javascripts/lang-sql.js",
    "examples/public/javascripts/lang-vb.js",
    "examples/public/javascripts/lang-wiki.js",
    "examples/public/javascripts/prettify.js",
    "examples/public/stylesheets/application.css",
    "examples/public/stylesheets/censor.css",
    "examples/public/stylesheets/coderay.css",
    "examples/public/stylesheets/prettify.css",
    "examples/public/stylesheets/pygments.css",
    "examples/public/stylesheets/syntax.css",
    "examples/public/stylesheets/uv.css",
    "examples/public/stylesheets/uv/amy.css",
    "examples/public/stylesheets/uv/blackboard.css",
    "examples/public/stylesheets/uv/cobalt.css",
    "examples/public/stylesheets/uv/dawn.css",
    "examples/public/stylesheets/uv/espresso_libre.css",
    "examples/public/stylesheets/uv/sunburst.css",
    "examples/public/stylesheets/uv/twilight.css",
    "examples/public/stylesheets/uv/zenburnesque.css",
    "examples/pygments.ru",
    "examples/pygments_api.ru",
    "examples/syntax.ru",
    "examples/ultraviolet.ru",
    "examples/views/index.erb",
    "examples/views/layout.erb",
    "lib/rack/codehighlighter.rb"
  ]
  s.homepage = %q{http://github.com/wbzyl/rack-codehighlighter}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Rack Middleware for Code Highlighting.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.1"])
      s.add_development_dependency(%q<rack-test>, [">= 0.3.0"])
    else
      s.add_dependency(%q<rack>, [">= 1.0.0"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.1"])
      s.add_dependency(%q<rack-test>, [">= 0.3.0"])
    end
  else
    s.add_dependency(%q<rack>, [">= 1.0.0"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.1"])
    s.add_dependency(%q<rack-test>, [">= 0.3.0"])
  end
end

